version: 2
updates:
  - package-ecosystem: pip
    cooldown:
      default-days: 7
    directory: /script
    groups:
      minor-updates:
        update-types: [minor, patch]
    schedule:
      interval: monthly
      day: tuesday
