name: approved-premises.application.assessed
title: Approved Premises Application Assessed
summary: A referral to an approved premises has been assessed
contentType: application/json
payload:
  type: object
  properties:
    eventType:
      type: string
      example: "approved-premises.application.assessed"
    version:
      type: integer
      example: 1
    detailUrl:
      type: string
      example: "https://approved-premises-api.hmpps.service.justice.gov.uk/events/application-assessed/38ade96c-d62c-4814-b202-7883d5f73605"
    occurredAt:
      type: string
      example: "2022-10-05T12:00:00.000Z"
    description:
      type: string
      example: "An Approved Premises application has been assessed"
    additionalInformation:
      type: object
      properties:
        applicationId:
          type: string
          example: "14547a9f-20e8-4643-8a15-402a7d8845fb"
    personReference:
      type: object
      properties:
        identifiers:
          type: array
          items:
            type: object
            properties:
              type:
                type: string
                example: "CRN"
              value:
                type: string
                example: "X371199"
