name: approved-premises.application.submitted
title: Approved Premises Application Submitted
summary: A referral to an approved premises has been submitted
contentType: application/json
payload:
  type: object
  properties:
    eventType:
      type: string
      example: "approved-premises.application.submitted"
    version:
      type: integer
      example: 1
    detailUrl:
      type: string
      example: "https://approved-premises-api.hmpps.service.justice.gov.uk/events/application-submitted/24b7ffa4-fe95-4ab8-9960-711168f00846"
    occurredAt:
      type: string
      example: "2022-10-05T12:00:00.000Z"
    description:
      type: string
      example: "A referral to an approved premises has been submitted"
    additionalInformation:
      type: object
      properties:
        applicationId:
          type: string
          example: "f917548d-95b5-4ef4-b8d4-abdb7a82fe21"
    personReference:
      type: object
      properties:
        identifiers:
          type: array
          items:
            type: object
            properties:
              type:
                type: string
                example: "CRN"
              value:
                type: string
                example: "X371199"
